sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

install: true

script:
  - ./gradlew clean build buildDockerImage -x test

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew pushDockerImages
    on:
      branch: master

script:
  - curl --insecure -X POST https://wmts-t.sogeo.services:9443/api/webhooks/6cafe370-d28d-4194-9495-b6b95e0ef58a
