sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

install: true

script:
  - ./gradlew clean build buildDockerImage -x test

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew pushDockerImages
    on:
      branch: master    
  # - provider: script
  #   skip_cleanup: true
  #   script: curl --insecure -X POST $PORTAINER_HOOK
  #   on:
  #     branch: master    

